TOPDIR ?= ../..
include $(TOPDIR)/.config

$(BEERCOUNTER_SUPPORT)_SRC += services/beercounter/beercounter.c
$(BEERCOUNTER_SUPPORT)_ECMD_SRC += services/beercounter/ecmd.c

##############################################################################
# generic fluff
include $(TOPDIR)/scripts/rules.mk
